class ReadQuery:

    READ_ALL_BARRIS = "SELECT CODI_BARRI, NOM_BARRI FROM CODI.BARRIS WHERE BAIXA='N'"
    READ_BARRI_BY_ID = "SELECT CODI_BARRI, NOM_BARRI FROM CODI.BARRIS WHERE CODI_BARRI = :1 AND BAIXA='N'"
    READ_BARRI_BY_NOM = "SELECT CODI_BARRI, NOM_BARRI FROM CODI.BARRIS WHERE NOM_BARRI LIKE :1 AND BAIXA='N'"

read_query = ReadQuery()
